import { Project } from './interfaces/project.model';

export const projects: Project[] = [
  {
    id: 1,
    title: 'PROJECTS.PROJECT1_TITLE',
    description: 'PROJECT_DETAIL.PROJECT1_DESC',
    implementationDetails: 'PROJECT_DETAIL.PROJECT1_IMPL',
    duration: 'PROJECT_DETAIL.PROJECT1_DURATION',
    used_tech: ['HTML', 'CSS', 'JavaScript'],
    image: '/assets/Images/MyProjects/Thumbnails/SharkieThumbnail.webp',
    animatedLineImage: '/assets/Images/AboutMe/AboutMeLine.webp',
    techIcons: [
      '/assets/Images/SkillSet/Logos/Frontend/HTML.webp',
      '/assets/Images/SkillSet/Logos/Frontend/CSS.webp',
      '/assets/Images/SkillSet/Logos/Frontend/JS.webp',
    ],
    repoLink: 'https://github.com/enesesine/Sharkie',
    liveDemo: 'https://sharkie.eneshadzic.com',
  },
  {
    id: 2,
    title: 'PROJECTS.PROJECT2_TITLE',
    description: 'PROJECT_DETAIL.PROJECT2_DESC',
    implementationDetails: 'PROJECT_DETAIL.PROJECT2_IMPL',
    duration: 'PROJECT_DETAIL.PROJECT2_DURATION',
    used_tech: ['HTML', 'CSS', 'JavaScript'],
    image: '/assets/Images/MyProjects/Thumbnails/JoinThumbnail.webp',
    animatedLineImage: '/assets/Images/AboutMe/AboutMeLine.webp',
    techIcons: [
      '/assets/Images/SkillSet/Logos/Frontend/HTML.webp',
      '/assets/Images/SkillSet/Logos/Frontend/CSS.webp',
      '/assets/Images/SkillSet/Logos/Frontend/JS.webp',
    ],
    repoLink: 'https://github.com/enesesine/Join',
    liveDemo: 'https://join.eneshadzic.com',
  },
  {
    id: 3,
    title: 'PROJECTS.PROJECT3_TITLE',
    description: 'PROJECT_DETAIL.PROJECT3_DESC',
    implementationDetails: 'PROJECT_DETAIL.PROJECT3_IMPL',
    duration: 'PROJECT_DETAIL.PROJECT3_DURATION',
    used_tech: ['HTML', 'CSS', 'JavaScript', 'Firebase'],
    image: '/assets/Images/MyProjects/Thumbnails/PokedexAPIThumbnail.webp',
    animatedLineImage: '/assets/Images/AboutMe/AboutMeLine.webp',
    techIcons: [
      '/assets/Images/SkillSet/Logos/Frontend/HTML.webp',
      '/assets/Images/SkillSet/Logos/Frontend/CSS.webp',
      '/assets/Images/SkillSet/Logos/Frontend/JS.webp',
      '/assets/Images/SkillSet/Logos/Frontend/Firebase.webp',
    ],
    repoLink: 'https://github.com/enesesine/Pokedex',
    liveDemo: 'https://pokedex.eneshadzic.com',
  },
  {
    id: 4,
    title: 'PROJECTS.PROJECT4_TITLE',
    description: 'PROJECT_DETAIL.PROJECT4_DESC',
    implementationDetails: 'PROJECT_DETAIL.PROJECT4_IMPL',
    duration: 'PROJECT_DETAIL.PROJECT4_DURATION',
    used_tech: ['Angular', 'CSS', 'Firebase'],
    image: '/assets/Images/MyProjects/Thumbnails/DABubblePlacehjolder.webp',
    animatedLineImage: '/assets/Images/AboutMe/AboutMeLine.webp',
    techIcons: [
      '/assets/Images/SkillSet/Logos/Frontend/Angular.webp',
      '/assets/Images/SkillSet/Logos/Frontend/CSS.webp',
      '/assets/Images/SkillSet/Logos/Frontend/Firebase.webp',
    ],
    repoLink: 'https://github.com/enesesine',
    liveDemo: '#',
  },
  {
    id: 5,
    title: 'PROJECTS.PROJECT5_TITLE',
    description: 'PROJECT_DETAIL.PROJECT5_DESC',
    implementationDetails: 'PROJECT_DETAIL.PROJECT5_IMPL',
    duration: 'PROJECT_DETAIL.PROJECT5_DURATION',
    used_tech: ['Angular', 'CSS', 'Firebase'],
    image: '/assets/Images/MyProjects/Thumbnails/DABubblePlacehjolder.webp',
    animatedLineImage: '/assets/Images/AboutMe/AboutMeLine.webp',
    techIcons: [
      '/assets/Images/SkillSet/Logos/Backend/Python.webp',
      '/assets/Images/SkillSet/Logos/Backend/Django.webp',
    ],
    repoLink: 'https://github.com/enesesine',
    liveDemo: '#',
  },
  {
    id: 6,
    title: 'PROJECTS.PROJECT6_TITLE',
    description: 'PROJECT_DETAIL.PROJECT6_DESC',
    implementationDetails: 'PROJECT_DETAIL.PROJECT6_IMPL',
    duration: 'PROJECT_DETAIL.PROJECT6_DURATION',
    used_tech: ['Angular', 'CSS', 'Firebase'],
    image: '/assets/Images/MyProjects/Thumbnails/DABubblePlacehjolder.webp',
    animatedLineImage: '/assets/Images/AboutMe/AboutMeLine.webp',
    techIcons: [
      '/assets/Images/SkillSet/Logos/Backend/Python.webp',
      '/assets/Images/SkillSet/Logos/Backend/Django.webp',
      '/assets/Images/SkillSet/Logos/Backend/Linux.webp',
    ],
    repoLink: 'https://github.com/enesesine',
    liveDemo: '#',
  },
];
